version: 2.1

setup: true

orbs: 
  continuation: circleci/continuation@0.2.0

parameters:
  python-version:
    type: string
    default: '3.8'
  is_foo:
    type: boolean
    default: false
    
jobs:
  init:
    resource_class: small
    docker:
      - image: cimg/python:<< pipeline.parameters.python-version >>
    steps:
      - checkout
      - run:
          name: set up parameters
          command: |
            jq --null-input '{}' > params.json
      - continuation/continue:
          configuration_path: .circleci/continued.yml
          parameters: params.json

workflows:
  # NOTE: there can only be 1 workflow here.
  # This is known as the "setup workflow" then.
  setup:
    jobs:
      - init
